---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renovate-operator
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: "renovate-s3"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    fullnameOverride: *app
    rbac:
      ownNamespaceOnly: true
    webhook:
      enabled: true
      # authentication:
      #   enabled: true
      #   secretRef:
      #     name: renovate-webhook
      #     key: WEBHOOK_TOKEN
