---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION: "{{ .AWS_REGION }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-db
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-db-credentials
    template:
      engineVersion: v2
      data:
        username: "{{ .RADARR_POSTGRES_USER }}"
        password: "{{ .RADARR_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: radarr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-db-credentials
    template:
      engineVersion: v2
      data:
        username: "{{ .SONARR_POSTGRES_USER }}"
        password: "{{ .SONARR_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: sonarr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr-db
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lieq44-db-credentials
    template:
      engineVersion: v2
      data:
        username: "{{ .LIDARR_POSTGRES_USER }}"
        password: "{{ .LIDARR_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: lidarr
