---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster.yaml
  - ./objectstore.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./externalsecret.yaml
  - ./service.yaml
  - ./pooler.yaml

  - ./databases/radarr.yaml
  - ./databases/sonarr.yaml
  - ./databases/lidarr.yaml
  - ./databases/prowlarr.yaml
