---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-nfs
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: media-nfs
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: media-nfs
  nfs:
    server: 172.16.20.7
    path: /Media
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - noatime
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 15Ti
