---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
  namespace: "${NAMESPACE}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        # KOPIA_REPOSITORY: "s3://kopia/${APP}"
        KOPIA_FS_PATH: /repository
        KOPIA_REPOSITORY: filesystem:///repository
        KOPIA_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        # KOPIA_S3_DISABLE_TLS: "true"
        # KOPIA_LOG_LEVEL: "debug"       # Shows logs in kubectl logs (console/stdout)
        # KOPIA_FILE_LOG_LEVEL: "debug"  # Saves logs to files in cache directory
        # KOPIA_LOG_DIR_MAX_FILES: "5"    # Keep only 5 log files
        # KOPIA_LOG_DIR_MAX_AGE: "5h"     # Keep logs for 5k  hours only
        # AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        # AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # AWS_S3_ENDPOINT: http://172.16.20.7:3900/
  dataFrom:
    - extract:
        key: volsync-template
