---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:=${APP}}"
  namespace: "${NAMESPACE}"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=5Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn}"
