---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-app-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: renovate
        property: RENOVATE_PRIVATE_KEY
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "2466666" # change to your GitHub App ID
  installID: "99449632" # change to your GitHub App Installation ID
  auth:
    privateKey:
      secretRef:
        name: github-app-pem # reference secret from step 1.
        key: private_key_pem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: renovate-secret
    template: # template secret to use  GITHUB_COM_TOKEN
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN:  "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
        # add additional fields you need, you can specify multiple sources in dataFrom to template more values in here
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
