---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .RENOVATE_GITHUB_PAT }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .RENOVATE_GITHUB_PAT }}"
  dataFrom:
    - extract:
        key: renovate
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: renovate
        property: RENOVATE_PRIVATE_KEY
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "2466666" # change to your GitHub App ID
  installID: "99449642" # change to your GitHub App Installation ID
  auth:
    privateKey:
      secretRef:
        name: github-app-pem # reference secret from step 1.
        key: private_key_pem
---
# 3. create a secret containing the required keys
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "30m0s"
  target:
    name: renovate-org-secret
    template: # template secret to use  GITHUB_COM_TOKEN
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN:  "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
        # add additional fields you need, you can specify multiple sources in dataFrom to template more values in here
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
