---
# yaml-language-server: $schema=https://github.com/mogenius/renovate-operator/raw/refs/heads/main/charts/renovate-operator/crds/renovate-operator.mogenius.com_renovatejobs.yaml
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
spec:
  # discoveryFilter:
  image: ghcr.io/renovatebot/renovate:42.52.2@sha256:813d39089b687166b691987d84753c13d3a95f6a5b9e048e9fe65c328072a63e
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@rphilipsen.nl>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379"
    - name: RENOVATE_DEPENDENCY_DASHBOARD
      value: "true"
---
# yaml-language-server: $schema=https://github.com/mogenius/renovate-operator/raw/refs/heads/main/charts/renovate-operator/crds/renovate-operator.mogenius.com_renovatejobs.yaml
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-docrphil
spec:
  image: ghcr.io/renovatebot/renovate:42.52.2@sha256:813d39089b687166b691987d84753c13d3a95f6a5b9e048e9fe65c328072a63e
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-org-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@rphilipsen.nl>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379"
    - name: RENOVATE_DEPENDENCY_DASHBOARD
      value: "true"
