---
# yaml-language-server: $schema=https://github.com/mogenius/renovate-operator/raw/refs/heads/main/charts/renovate-operator/crds/renovate-operator.mogenius.com_renovatejobs.yaml
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: "renovate-s3"
spec:
  # discoveryFilter:
  image: ghcr.io/renovatebot/renovate:42.50.0@sha256:420532c2770bf504f3f9f4484ba930367f78c95268e4f33621144d8429104a15
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@rphilipsen.nl>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379"
    - name: RENOVATE_DEPENDENCY_DASHBOARD
      value: "true"
    - name: RENOVATE_FORK_PROCESSING
      value: "disabled"
    - name: RENOVATE_S3_ENDPOINT
      value: "http://172.16.20.7:3900/"
    - name: RENOVATE_S3_PATH_STYLE
      value: "true"
    - name: RENOVATE_S3_BUCKET
      value: "renovate"
    - name: RENOVATE_REPOSITORY_CACHE
      value: "enabled"
    - name: RENOVATE_REPOSITORY_CACHE_TYPE
      value: "s3://renovate/"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: renovate-s3
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: renovate-s3
          key: AWS_SECRET_ACCESS_KEY

