---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
spec:
  # discoveryFilter:
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@rphilipsen.nl>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_REDIS_URL
      value: "redis://dragonfly.database.svc.cluster.local:6379"
    - name: RENOVATE_DEPENDENCY_DASHBOARD
      value: "true"
  image: ghcr.io/renovatebot/renovate:42.46.0@sha256:52db3f829ab28078210aa9d3a872e8707269a932070ef84c319bb6b18297b682
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-secret
