---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-secret
    template:
      data:
        "1pw_credentials_json": "{{ .credentials }}"
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: 1pwconnect
