---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: garage-nfs
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-nfs
  namespace: database
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: garage-nfs
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: database
    name: garage-nfs-data
  nfs:
    server: 172.16.20.7
    path: /Media
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - noatime
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-nfs-data
  namespace: database
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: garage-nfs-data
  resources:
    requests:
      storage: 15Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-nfs-meta
  namespace: database
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: garage-nfs
  capacity:
    storage: 15Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: database
    name: garage-nfs
  nfs:
    server: 172.16.20.7
    path: /Media
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - noatime
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-nfs-meta
  namespace: database
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 15Ti
