---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-secret

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: webhook-secret
    template:
      engineVersion: v2
      data:
        GITHUB_WEBHOOK_SECRET: "{{ .WEBHOOK_TOKEN }}"

  dataFrom:
    - extract:
        key: renovate
