---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app garage-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: garage
  values:
    controllers:
      garage-webui:
        annotations:
          secret.reloader.stakater.com/reload: garage-secret
        containers:
          app:
            image:
              repository: khairul169/garage-webui
              tag: 1.1.0@sha256:17c793551873155065bf9a022dabcde874de808a1f26e648d4b82e168806439c
            env:
              API_BASE_URL: http://192.168.0.10:3903
              S3_ENDPOINT_URL: http://192.168.0.10:3900
              API_ADMIN_KEY:
                valueFrom:
                  secretKeyRef:
                    name: garage-secret
                    key: GARAGE_ADMIN_TOKEN
            envFrom:
              - secretRef:
                  name: garage-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        ports:
          http:
            port: &port 3909
    route:
      app:
        hostnames: ["garageui.rphilipsen.nl"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    configMaps:
      config:
        data:
          configuration.toml: |
            metadata_dir = "/meta"
            data_dir = "/data"
            db_engine = "sqlite"
            metadata_auto_snapshot_interval = "6h"

            replication_factor = 1
            compression_level = 2

            rpc_bind_addr = "[::]:3901"
            rpc_public_addr = "127.0.0.1:3901"

            [s3_api]
            s3_region = "us-east-1"
            api_bind_addr = "[::]:3900"
            root_domain = ".s3.rphilipsen.nl"

            [s3_web]
            bind_addr = "[::]:3902"
            root_domain = ".s3web.rphilipsen.nl"
            add_host_to_metrics = true

            [admin]
            api_bind_addr = "[::]:3903"
    persistence:
      config:
        enabled: true
        type: configMap
        name: garage-webui
        globalMounts:
          - path: /etc/garage.toml
            subPath: configuration.toml
