---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name lldap-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_ADMIN_USERNAME: "{{ .LLDAP_ADMIN_USERNAME }}"
        LLDAP_ADMIN_PASSWORD: "{{ .LLDAP_ADMIN_PASSWORD }}"
        LLDAP_LDAP_BASE_DN: "{{ .LLDAP_LDAP_BASE_DN }}"
        LLDAP_DATABASE_URL: "postgres://{{ .LLDAP_POSTGRES_USER }}:{{ .LLDAP_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local/lldap"
  dataFrom:
    - extract:
        key: lldap