---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname internal.rphilipsen.nl
  labels:
    gateway: internal
spec:
  allowedListeners:
    namespaces:
      from: All
  gatewayClassName: agentgateway
  addresses:
    - type: IPAddress
      value: 172.16.20.31
    # - type: IPAddress
    #   value: 2a02:a446:fe34:20:172:16:20:31
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: 172.16.20.31
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.rphilipsen.nl"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.rphilipsen.nl"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
          - kind: TLSRoute
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: rphilipsen-nl-tls
    - name: trees100-https
      hostname: "*.trees100.nl"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: trees100-nl-tls
